jobs:
  build:

  deploy:
  name: Deploy
  needs: build
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main'

  step:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: production-files
        path: ./dist

    - name: Deploy to Github Pages
      uses: peaceiris/action-gh-pages@v3
      with:
        github_token: ${{ secret.GITHUB_TOKEN }}
        publish_dir: ./dist